from pathlib import Path
from datetime import datetime,date,timedelta
from zoneinfo import ZoneInfo
from icalendar import Calendar
import json
ROOT=Path(__file__).resolve().parent
D=ROOT/'downloads'
def link(p,label=None):return f'[{label or p.name}](<{p.as_posix()}>)'
def find(pattern):return next(D.rglob(pattern))
fm=next(D.glob('Financial*'));kom=next(D.glob('Kwalitatieve*'));mot=next(D.glob('Management*'))
md=['# Recommended weekly study checklist — Semester 1a 2026', '', 'Prepared 8 September 2026 from downloaded Brightspace content and the existing personalized calendar (saved 6 September). All times Europe/Amsterdam. Study durations are recommendations; class times come from your calendar. This plan supersedes the earlier draft.', '', '## Your groups', '', '| Course | Group | Tutorial |', '|---|---|---|', '| Financial Management BDK | Group 1 | Tuesday 13:00–15:00, 5419.0007 |','| Management- en Organisatietheorie | Werkcollege 3, Groepje 3 | Thursday 13:00–15:00, 5416.0059 |','| Kwalitatieve onderzoeksmethoden | Werkcollege 3, Team 8 (3.8) | Friday 11:00–13:00, 5433.0209A |','', 'Use the dated sessions below: tutorials do not occur every week. KOM feedback meetings may use a shorter team-specific slot within the calendar block.', '', '## This week: 8–13 September', '', '- [ ] **Tuesday:** attend FM tutorial 13:00–15:00; afterwards redo incorrect chapter 1–5/14 questions (60–90 min). Coordinate the Google case with M&OT subgroup 3 (30 min).', '- [ ] **Wednesday:** practise FM financial statements, ratios, present/future values and annuities (2 hours). Watch M&OT modules 2.1–2.3 and read the Google case literature (2 hours). Attend KOM Q&A at 13:00 if useful; calendar reserves 13:00–14:00.', '- [ ] **Thursday morning:** finish Google case questions 1a–2c and the Mintzberg table with subgroup 3 (90 min). Attend M&OT 13:00–15:00 and FM lecture 15:00–17:00. Allow for the immediate room change.', '- [ ] **Before Friday 11:00:** watch KOM videos 6–9; draft the research design and interview guide with Team 8 (2–3 hours). Use the tutorial-2 worksheet.', '- [ ] **Friday during KOM 11:00–13:00:** finish and upload the team worksheet before class ends (worksheet instruction). Use filename prefix **03_08** followed by the assignment title. The worksheet says to export PDF; the Brightspace content page says DOCX. Keep both versions and check the submission box or instructor for the accepted format. Brightspace closes at **17:00**; keep the upload receipt.', '- [ ] **Friday 15:00:** sit the FM test, **tentamenhal 4** (calendar room 5263.0226, booked until 17:00). Bring calculator, pen and student ID. It covers **chapters 1, 2, 3, 4, 5 and 14**, contains 12 calculation questions and counts for 10%.', '- [ ] **Weekend:** do FM H6: 11,19,22,24 and H7: 1,3,26,27 for Tuesday 15 September (2 hours). Revise the Google case after feedback; prepare for the handbook deadline Wednesday 16 September 09:00. Outline KOM team assignment 1 and divide its chapters (90 min).', '', 'M&OT: the handbook requires the presenting subgroup to email its draft to the feedback subgroup by Wednesday 09:00. Your subgroup is **3**; its presentation/feedback rotation has not been verified, so the earlier draft’s subgroup-1 instructions are not assigned to you. Confirm the rotation with your instructor/team.', '', '### Immediate source files', '']
for p in [find('Informatie vooraf.html'),find('Werkcollege2.pdf'),find('*Google*.docx'),find('MOT2026_Cursushandleiding*.doc'),find('Cursusplanning.html')]:md.append('- '+link(p))
md+=['','## Recommended weekly rhythm','','Budget about 8–12 independent study hours per course per week, adjusting to workload and what you have already completed. The blocks below are anchors; use additional blocks for reading, practice and group work.','','- **Monday:** FM tutorial exercises (2 h); M&OT readings, virtual lecture and draft case (2–3 h).','- **Tuesday:** FM tutorial; M&OT report edits and submission checks (1–2 h), ready before Wednesday 09:00.','- **Wednesday:** KOM videos/reading and project work (2–3 h); Q&A; finish Thursday’s M&OT case.','- **Thursday:** M&OT tutorial and FM lecture where scheduled; prepare KOM worksheet (1–2 h).','- **Friday:** KOM tutorial and prompt upload; complete available FM practice quiz and note errors (1 h).','- **Weekend:** project milestone work and next Tuesday’s FM exercises; reserve a catch-up block.','','## Week-by-week checklist and actual calendar sessions','']
weeks=[
('2026-09-14','FM: study H8 and H17 for Thursday; Tuesday tutorial uses H6/H7 exercises listed above. After Thursday, practise Quiz 2 (H6,7,8,17); its calendar entry is 17 September 17:00, not a verified closing deadline.','M&OT: prepare Google final report by Wed 16 Sep 09:00 per handbook; prepare Brandweer part 1 using Bourne & Jenkins (2012), Williams & Mihaylo (2019), Qi et al. (2019). Case materials not yet published in the downloaded TOC.','KOM: prepare individual Werkcollege 3 document for Friday interview training. Finish and proofread team assignment 1 by Sunday evening, ready for Monday 21 Sep 09:00; agree interview respondents and provisional dates.'),
('2026-09-21','FM: Tuesday exercises H8: 3,12,19,27; H17: 1,7,17. Read H9–11 before Thursday; practise Quiz 3 when available (calendar 24 Sep 17:00).','M&OT: handbook final assignment 2 Wed 23 Sep 09:00; prepare Brandweer part 2, Daft H13–14. Confirm subgroup 3’s presenting/feedback role.','KOM: submit team assignment 1 Monday 09:00. Review feedback in Friday’s team meeting; confirm Team 8’s exact slot. Watch videos 10–13 when released (brochure: 21 Sep), read corresponding H10,11,13. Conduct interviews after feedback and before tutorial 5.'),
('2026-09-28','FM: Tuesday exercises H9: 1,3,7,11,19; H10: 3,5,11; H11: 9,12,21. Read H12–13 before Thursday; practise Quiz 4 (calendar 1 Oct 17:00).','M&OT: handbook final assignment 3 Wed 30 Sep 09:00; prepare final case part 1, Daft H12 and Probst & Raisch (2005).','KOM: attend Wednesday data-analysis lecture. Watch videos 14–16 when released (brochure: 28 Sep); read H8–9. Have interview transcript usable for Friday tutorial 5; upload worksheet before class ends (Brightspace closes Fri 2 Oct 17:00). Begin coding and retain audio securely.'),
('2026-10-05','FM: Tuesday exercises H12: 1,6,9,11; H13: 2,3,5,7,13,15. Read H15–16 before Thursday; practise Quiz 5 (calendar 8 Oct 17:00).','M&OT: handbook final assignment 4 Wed 7 Oct 09:00; prepare final case part 2, Daft H6 and Zahra & George (2002).','KOM: submit transcript and audio fragment Thu 8 Oct 17:00. Complete coding, analysis and draft advice for team assignment 2; test Atlas.ti project export. No Friday KOM tutorial appears in this week’s calendar.'),
('2026-10-12','FM: Tuesday exercises H15: 1,3,10,13,14; H16: 5,11,13. Use the old exams and formula sheet for timed practice; repair weak topics. Exam-preparation calendar entry is Wed 14 Oct 16:00.','M&OT: handbook final assignment 5 Wed 14 Oct 09:00; attend Tuesday closing lecture. Build a theory-to-case comparison sheet for exam revision.','KOM: submit BOTH team assignment 2 and Project Bundel – Atlas.ti Wed 14 Oct 17:00. Check uploads independently. Prepare for Friday tutorial and consolidate all 16 videos/assigned book chapters. Complete the required 50-minute Sona lab session during the block if still outstanding (brochure); verify recorded credit.'),
('2026-10-19','FM: final error-log review on Monday; exam Tuesday 20 October 11:45. Use the calendar below for finish time and room.','M&OT: practise applying each theory to unfamiliar cases; alternate timed answers with reading weak chapters.','KOM: practise explaining research design, sampling, interviews, validity, ethics and coding without notes; use short daily recall sessions and a mock exam if provided.'),
('2026-10-26','FM: file exam notes and any follow-up actions.','M&OT: targeted revision Monday–Wednesday; exam Thursday 29 October 11:45.','KOM: final review Monday; exam Tuesday 27 October 11:45. After the exam, shift remaining revision time to M&OT.')]
cal=Calendar.from_ical((D/'personalized_schedule.ics').read_bytes())
for start,*tasks in weeks:
 s=date.fromisoformat(start);e=s+timedelta(days=6)
 md += [f'### {s:%d %B}–{e:%d %B %Y}','']
 md += ['- [ ] '+t for t in tasks]
 md+=['','**Calendar sessions**','']
 for ev in sorted(cal.walk('VEVENT'),key=lambda v:v.decoded('dtstart')):
  dt=ev.decoded('dtstart');end=ev.decoded('dtend')
  if s<=dt.date()<=e:md.append(f'- {dt:%a %d %b %H:%M}–{end:%H:%M}: {ev.get("summary")} — {ev.get("location", "Location not listed")}')
 md+=['']
md+=['## Verified assignment dates','','Due dates and closing times below come directly from Brightspace assignment records. A closing time is not necessarily the instructor’s preferred submission time.','']
for c in json.loads((D/'course-deadlines.json').read_text(encoding='utf-8')):
 for a in c['sources']['assignments']['data']:
  val=a.get('DueDate') or a.get('Availability',{}).get('EndDate')
  if val:
   dt=datetime.fromisoformat(val.replace('Z','+00:00')).astimezone(ZoneInfo('Europe/Amsterdam'))
   if dt.date()>=date(2026,9,8):md.append(f'- **{dt:%d %b %H:%M}** — {a["Name"]} ({"due" if a.get("DueDate") else "closes"}).')
md+=['','M&OT handbook deadlines: final reports 1–5 on **16 Sep, 23 Sep, 30 Sep, 7 Oct, 14 Oct**, each **Wednesday 09:00**. Confirm the assessed deliverables for your subgroup’s rotation; no M&OT dropbox dates were returned.','','## Materials and limitations','', '- '+link(D/'materials_index.md','Browse downloaded materials by course and module'),'- '+link(D/'course-deadlines.json','Live Brightspace calendar and assignment snapshot'),'- '+link(D/'personalized_schedule.ics','Original group-filtered calendar'),'- '+link(find('Brochure*.pdf'),'KOM course brochure'),'', 'Files reflect material accessible on 8 September. Later M&OT cases and KOM videos 10–16 were not yet listed as downloadable content. External/LTI activities remain links and require the provider; the nine embedded KOM MP4 files are downloaded separately. Textbooks and references mentioned by title are not automatically available as files. Quiz calendar entries are reminders/opening markers, not assumed submission deadlines; the standalone quiz API was unavailable. Recheck Brightspace announcements and new uploads weekly.']
(ROOT/'recommended_weekly_todo.md').write_text('\n'.join(md)+'\n',encoding='utf-8')
print('Wrote recommended_weekly_todo.md')
